# Generated by Django 6.0.4 on 2026-08-26 15:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_control', '0017_rename_fecha_recepcion_envio_fecha_cierre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pastillero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('cantidad', models.IntegerField(default=1, help_text='Cantidad de comprimidos/unidades tomadas')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomas_pastillero', to='medicine_control.insumo')),
            ],
            options={
                'verbose_name': 'Registro de Pastillero',
                'verbose_name_plural': 'Pastillero',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
